SELECT * FROM ORDERS
;

SELECT SUM(PRICE) FROM ORDER_DETAILS
WHERE ORDERNUMBER IN (
SELECT ORDERNUMBER FROM ORDERS WHERE ORDERDATE BETWEEN '2003-01-01' AND '2004-12-31'
)
;

SELECT SUM(PRICE) FROM ORDER_DETAILS
WHERE ORDERNUMBER IN (
SELECT ORDERNUMBER FROM ORDERS WHERE ORDERDATE BETWEEN '2003-01-01' AND '2003-12-31'
)
;

SELECT SUM(QUANTITYORDERED) FROM ORDER_DETAILS
WHERE ORDERNUMBER IN (
SELECT ORDERNUMBER FROM ORDERS WHERE ORDERDATE BETWEEN '2003-01-01' AND '2004-12-31'
)
;

SELECT COUNT(DISTINCT ORDERNUMBER) FROM ORDER_DETAILS
;

SELECT E.EMPLOYEENUMBER,FIRSTNAME,SUM(PRICE) SALES FROM ORDER_DETAILS O
JOIN EMPLOYEES E
ON E.EMPLOYEENUMBER = O.EMPLOYEENUMBER
WHERE ORDERNUMBER IN (
SELECT ORDERNUMBER FROM ORDERS WHERE ORDERDATE BETWEEN '2003-01-01' AND '2004-12-31'
)
GROUP BY E.EMPLOYEENUMBER,FIRSTNAME
ORDER BY SALES DESC
;

SELECT O.ORDERNUMBER,CUSTOMERNAME,COUNTRY,STATE,CITY,CREDITLIMIT,SUM(PRICE) SALES FROM ORDER_DETAILS O
JOIN CUSTOMERS E
ON E.CUSTOMERNUMBER= O.CUSTOMERNUMBER
WHERE ORDERNUMBER IN (
SELECT ORDERNUMBER FROM ORDERS WHERE ORDERDATE BETWEEN '2003-01-01' AND '2004-12-31'
)
GROUP BY O.ORDERNUMBER,CUSTOMERNAME,COUNTRY,STATE,CITY,CREDITLIMIT
ORDER BY ORDERNUMBER ASC
;

SELECT O.ORDERNUMBER,FIRSTNAME,SUM(PRICE) SALES FROM ORDER_DETAILS O
JOIN EMPLOYEES E
ON E.EMPLOYEENUMBER= O.EMPLOYEENUMBER
WHERE ORDERNUMBER IN (
SELECT ORDERNUMBER FROM ORDERS WHERE ORDERDATE BETWEEN '2003-01-01' AND '2004-12-31'
)
GROUP BY O.ORDERNUMBER,FIRSTNAME
ORDER BY ORDERNUMBER ASC
;
